---
platform: linux

image_resource:
  type: docker-image
  source: { repository: getourneau/alpine-bash-git }

inputs:
- name: node-red
- name: node-red-config

outputs:
- name: build-output

run:
  path: node-red-config/scripts/ci
