jobs:
- name: deploy-node-red-with-custom-private-node
  public: false
  plan:
  - aggregate:
    - get: node-red
    - get: node-red-config
      trigger: true
  - task: integrate
    file: node-red-config/integrate.yml
  - put: pcf-dev
    params:
      manifest: integrate-output/manifest.yml
      current_app_name: node-red

resources:
- name: pcf-dev
  type: cf-docker-resource
  source:
    api: https://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: pcfdev-space
    skip_cert_check: true
- name: node-red
  type: github-resource
    source:
      user: node-red
      repository: node-red
- name: node-red-config
  type: git
    source:
      uri: https://github.com/idahobean/node-red-config
