#!/bin/bash

set -eu

unzip -d integrate-output node-red/node-red-*.zip && f=(integrate-output/*) && mv integrate-output/*/* integrate-output && rmdir "${f[@]}"
mv node-red-config/config/* integrate-output -f

find .
